name: CI checks
on: push
jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.2.1
        with:
          go-version: 1.18
      - run: make format-check
      - run: make lint
      - run: make build
      - run: make test
