name: CI checks
on: push
jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - run: make format-check
      - run: make lint
      - run: make build
      - run: make test
