name: release
on:
  push:
    tags:
      - "v*"
jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: make lint
      - run: make build
      - run: make test
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ env.GITHUB_REF }}
          files: |
            LICENSE
            bin/*-aws-cfg-generator
